
[package]
name = "PIPEWIRE_YOLO_STREAMING"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.52.1", features = ["full"] }
tokio-util = { version = "0.7", features = ["full"] }
tokio-stream = "0.1.19"
# Utiles varios necesarios:
uuid = { version = "1.10", features = ["v4"] }
serde = "1.0.229"
serde_json = "1.0.151"
bitflags = "2.13.1"

# Listas y otras herramientas para programación concurrente
crossbeam = "0.8.5"

# Para codificar/transformar los pixeles BGRA en H264 u otros.
ffmpeg-the-third = "6.0.0"

# Para comunicación con Compositor de escritorio KWin
zbus = "5.18.0"

# Comunicación con Servidor Multimedia PipeWire
pipewire = { version = "0.10.1", features = ["v0_3_65"] }
# Doc: https://docs.rs/pipewire-native/latest/pipewire_native/ (solo funciona para audio) # pipewire-native = { path = "./dependencies/pipewire-native-rs/pipewire" }

# Para comunicación con Kernel (especificamente con GPU NVIDIA)
libc = "0.2"
# Para trabajar con DMA (Direct Memory Access) de Hardware (GPU este caso)
dma-buf = "0.5.0"
# Contiene los flags "DRM_*"
drm-fourcc = "2.2.0"
bytes = "1.12.1"



#wayland-client = "0.31.15"
#wayland-backend = "0.3.16"
#wayland-scanner = "0.31.11"






