 // Autogenerated code

pub mod zkde_screencast{

    use wayland_client;
    use wayland_client::protocol::*;


    pub mod __interfaces {
        use wayland_client::protocol::__interfaces::*;
        wayland_scanner::generate_interfaces!("protocols/not-available/zkde-screencast-unstable-v1.xml");
    }


    use __interfaces::{ ZKDE_SCREENCAST_UNSTABLE_V1_INTERFACE,ZKDE_SCREENCAST_STREAM_UNSTABLE_V1_INTERFACE};
    wayland_scanner::generate_client_code!("protocols/not-available/zkde-screencast-unstable-v1.xml");


    pub use self::zkde_screencast_unstable_v1::Pointer;

}


pub mod screencast;
